"use client"

import { useEffect, useState } from "react"
import { Loader2, Plus, Trash2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { useToast } from "@/components/Toast"
import { createMailRule, deleteMailRule, getMailRules, type MailRule } from "@/lib/api/mail-rules"

export function MailRulesDialog({ channelId, open, onOpenChange }: { channelId: number; open: boolean; onOpenChange: (open: boolean) => void }) {
  const [rules, setRules] = useState<MailRule[]>([]); const [value, setValue] = useState(""); const [type, setType] = useState<MailRule["type"]>("allow"); const [valueType, setValueType] = useState<MailRule["value_type"]>("email"); const [loading, setLoading] = useState(false); const { addToast } = useToast()
  const load = async () => { setLoading(true); try { setRules((await getMailRules(channelId)).data) } catch (error) { addToast({ type: "error", title: "No se pudieron cargar las reglas", description: error instanceof Error ? error.message : undefined }) } finally { setLoading(false) } }
  useEffect(() => { if (open) void load() }, [open, channelId])
  const add = async () => { if (!value.trim()) return; try { const { data } = await createMailRule(channelId, { type, value_type: valueType, value: value.trim() }); setRules((current) => [...current, data]); setValue("") } catch (error) { addToast({ type: "error", title: "Regla inválida", description: error instanceof Error ? error.message : undefined }) } }
  const remove = async (rule: MailRule) => { try { await deleteMailRule(channelId, rule.id); setRules((current) => current.filter((item) => item.id !== rule.id)) } catch (error) { addToast({ type: "error", title: "No se pudo eliminar la regla", description: error instanceof Error ? error.message : undefined }) } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Reglas de email</DialogTitle><DialogDescription>Los permitidos entran directo; los bloqueados se descartan antes de crear contactos.</DialogDescription></DialogHeader><div className="grid gap-2 sm:grid-cols-[130px_120px_1fr_auto]"><Select value={type} onValueChange={(next) => setType(next as MailRule["type"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="allow">Permitir</SelectItem><SelectItem value="block">Bloquear</SelectItem></SelectContent></Select><Select value={valueType} onValueChange={(next) => setValueType(next as MailRule["value_type"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="email">Email</SelectItem><SelectItem value="domain">Dominio</SelectItem></SelectContent></Select><Input value={value} onChange={(event) => setValue(event.target.value)} placeholder={valueType === "email" ? "cliente@empresa.com" : "empresa.com"} /><Button onClick={() => void add()}><Plus className="size-4" /></Button></div><div className="max-h-64 overflow-y-auto rounded-lg border border-border">{loading ? <div className="flex justify-center p-6"><Loader2 className="size-4 animate-spin" /></div> : rules.length === 0 ? <p className="p-5 text-center text-sm text-muted-foreground">Todavía no hay reglas.</p> : rules.map((rule) => <div key={rule.id} className="flex items-center gap-2 border-b border-border px-3 py-2 last:border-0"><span className={`text-xs font-medium ${rule.type === "allow" ? "text-emerald-600" : "text-destructive"}`}>{rule.type === "allow" ? "Permitir" : "Bloquear"}</span><span className="text-xs text-muted-foreground">{rule.value_type}</span><span className="min-w-0 flex-1 truncate text-sm">{rule.value}</span><Button variant="ghost" size="icon" className="size-7 text-muted-foreground hover:text-destructive" onClick={() => void remove(rule)}><Trash2 className="size-3.5" /></Button></div>)}</div></DialogContent></Dialog>
}
